apply plugin: 'com.android.application'

android {
    namespace 'com.example.autoskip'
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.example.autoskip"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        release {
            storeFile file("../zenskip.keystore")
            storePassword "zenskip123"
            keyAlias "zenskip"
            keyPassword "zenskip123"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.10.3'
    testImplementation 'androidx.test:core:1.5.0'
}
